<?
//  Organization's logo picture (blank if none)
    $org_logo = "../images/om_webmail.gif";

//  Organization's name
    $org_name = "Operation Mobilization";

//  Webmail Title
//  This is the title that goes at the top of the browser window
    $org_title = "OM-USA WebMail";

//  The server that your imap server is on
    $imapServerAddress = "localhost";
    $imapPort = 143;

//  The domain where your email address is.
//   Example:  in "luke@usa.om.org", usa.om.org is the domain.
//             this is for all the messages sent out.  Reply address
//             is generated by $username@$domain
    $domain = "localhost";

//  Your SMTP server and port number (usually the same as the IMAP server)
    $smtpServerAddress = "localhost";
    $smtpPort = 25;

//  This is displayed right after they log in
    $motd = "  Welcome to OM's webmail system, SquirrelMail.  We are currently in beta, and have not yet released a full version of SquirrelMail.  Please feel free to look around, and please report any bugs to <A HREF=\"mailto:nathan@usa.om.org\">Nathan</A> or <A HREF=\"mailto:luke@usa.om.org\">Luke</A>.";

//  Customizable colors
    $color[0]   = "DCDCDC"; // Light Gray
    $color[1]   = "800000"; // Red
    $color[2]   = "CC0000"; // Light Red
    $color[3]   = "A0B8C8"; // Left Background
    $color[4]   = "FFFFFF"; // Background
    $color[5]   = "FFFFCC"; // Light Yellow
    $color[6]   = "000000"; // Left Text
    $color[7]   = "0000CC"; // Link
    $color[8]   = "000000"; // Text
    $color[9]   = "ABABAB"; // Darker light gray
    $color[10]  = "666666"; // Darker light gray
    $color[11]  = "770000"; // Special folder color

//  Whether or not to use $color[11] for special folders.  If not, special
//  folders will be the same color as the other folders
    $use_special_folder_color = true;

/* The following are related to deleting messages.
 *   $move_to_trash
 *         - if this is set to "true", when "delete" is pressed, it will attempt
 *           to move the selected messages to the folder named $trash_folder.  If
 *           it's set to "false", we won't even attempt to move the messages, just
 *           delete them.
 *   $trash_folder
 *         - This is the path to the default trash folder.  For Cyrus IMAP, it
 *           would be "INBOX.Trash", but for UW it would be "Trash".  We need the
 *           full path name here.
 *   $auto_expunge
 *         - If this is true, when a message is moved or copied, the source mailbox
 *           will get expunged, removing all messages marked "Deleted".
 */

    $move_to_trash = true;
    $trash_folder = "INBOX.Trash";
    $auto_expunge = true;

//  Special Folders are folders that can't be manipulated like normal user created
//  folders can.  A couple of examples would be "INBOX.Trash", "INBOX.Drafts".  We have
//  them set to Netscape's default mailboxes, but this obviously can be changed.
//  To add one, just add a new number to the array.

    $special_folders[0] = "INBOX";   // The first one has to be the inbox (whatever the name is)
    $special_folders[1] = $trash_folder;
    $special_folders[2] = "INBOX.Sent";
    $special_folders[3] = "INBOX.Drafts";
    $special_folders[4] = "INBOX.Templates";

//  Whether or not to list the special folders first  (true/false)
    $list_special_folders_first = true;

//  Are all your folders subfolders of INBOX (i.e.  cyrus IMAP server)
//  If you are not sure, set it to false.
    $default_sub_of_inbox = true;

//  Some IMAP daemons (UW) handle folders weird.  They only allow a folder to contain
//  either messages or other folders, not both at the same time.  This option controls
//  whether or not to display an option during folder creation.  The option toggles
//  which type of folder it should be.
//
//  If this option confuses you, make it "true".  You can't hurt anything if it's true,
//  but some servers will respond weird if it's false.  (Cyrus works fine whether it's
//  true OR false).
    $show_contain_subfolders_option = false;

//  Whether or not to use META tags and automatically forward after an action has
//  been completed.
    $auto_forward = true;
?>
