#!/bin/sh

# **
# ** This script merges global PO to locale PO files.
# ** It creates a squirrelmail.po.new that have to
# ** be renamed to squirrelmail.po once before to
# ** compile the file.
# **
# ** Usage:   mergepo <locale id>
# ** Example: mergepo es
# **
# ** Philipe Mingo <mingo@rotedic.com>
# ** Konstantin Riabitsev <icon@duke.edu>
# **
# **  $Id$

if [ -z "$1" ]; then
 echo "USAGE: mergepo [localename]"
 exit 1
fi

WORKDIR=../locale
LOCALEDIR=$WORKDIR/$1

if [ ! -d $LOCALEDIR ]; then
 # lessee if it's been renamed.
 DCOUNT=`find $WORKDIR/ -name $1* | wc -l` 
 if [ $DCOUNT -eq 1 ]; then 
  # aha
  LOCALEDIR=`find $WORKDIR/ -name $1*`
 elif [ $DCOUNT -gt 1 ]; then
  # err out
  echo "More than one locale matching this name found:"
  find $WORKDIR/ -name $1*
  echo "You have to be more specific."
  exit 1
 fi
fi

echo "Merging $LOCALEDIR/LC_MESSAGES/squirrelmail.po"
mv $LOCALEDIR/LC_MESSAGES/squirrelmail.po \
     $LOCALEDIR/LC_MESSAGES/squirrelmail.po.bak 
msgmerge $LOCALEDIR/LC_MESSAGES/squirrelmail.po.bak ../po/squirrelmail.po > \
     $LOCALEDIR/LC_MESSAGES/squirrelmail.po
echo "Old po file renamed to squirrelmail.po.bak "
