#!/bin/sh

# **
# ** This script regenerates main PO file
# **
# ** Philipe Mingo <mingo@rotedic.com>
# ** 
# **  $Id$ 
cd ../..
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail \
    --no-location -C squirrelmail/src/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/functions/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/class/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/class/mime/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/class/deliver/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/class/helper/*.php --output=squirrelmail/po/squirrelmail.pot    
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/include/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/include/options/*.php --output=squirrelmail/po/squirrelmail.pot
    
# ** Plugins
    
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/abook_take/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/administrator/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/bug_report/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/calendar/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/filters/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/fortune/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/info/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/listcommands/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/mail_fetch/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/message_details/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/newmail/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/sent_subfolders/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
   --no-location  -C squirrelmail/plugins/spamcop/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/squirrelspell/*.php --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/squirrelspell/modules/*.mod \
    --output=squirrelmail/po/squirrelmail.pot
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/plugins/translate/*.php --output=squirrelmail/po/squirrelmail.pot

xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    --no-location -C squirrelmail/po/independent_strings.txt --output=squirrelmail/po/squirrelmail.pot

cd squirrelmail/po
