#!/bin/bash

# **
# ** This script regenerates main PO file
# **
# ** Philipe Mingo <mingo@rotedic.com>
# ** 
# **  $Id$ 
cd ../..
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail \
    -C squirrelmail/src/*.php --output-dir=squirrelmail/po/
xgettext --keyword=_ -keyword=N_  --default-domain=squirrelmail -j \
    -C squirrelmail/functions/*.php --output-dir=squirrelmail/po/
cd squirrelmail/po