#!/bin/sh

# **
# ** This script compiles locale PO files
# **
# ** Usage:   compilepo <locale id>
# ** Example: compilepo es
# **
# ** Philipe Mingo <mingo@rotedic.com>
# **
# **  $Id$

msgfmt -o $1/LC_MESSAGES/squirrelmail.mo $1/LC_MESSAGES/squirrelmail.po

