#!/bin/sh

# **
# ** This script merges global PO to locale PO files.
# ** It creates a squirrelmail.po.new that have to
# ** be renamed to squirrelmail.po once before to
# ** compile the file.
# **
# ** Usage:   mergepo <locale id>
# ** Example: mergepo es
# **
# ** Philipe Mingo <mingo@rotedic.com>
# **
# **  $Id$

mv $1/LC_MESSAGES/squirrelmail.po $1/LC_MESSAGES/squirrelmail.po.bak 
msgmerge $1/LC_MESSAGES/squirrelmail.po.bak ../po/squirrelmail.po > $1/LC_MESSAGES/squirrelmail.po
echo "Old po file renamed to squirrelmail.po.bak "
